import mock from "../mock";

let data = [
  {
    camada: { id: 1, title: "Banco de Dados" },
    nome: "SNELNX8876",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 2, title: "Banco de Dados" },
    nome: "SNELNX8877",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 3, title: "Banco de Dados" },
    nome: "SNELNX8878",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 4, title: "Banco de Dados" },
    nome: "SNELNX8879",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 5, title: "Banco de Dados" },
    nome: "SNELNX8880",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 6, title: "Mista" },
    nome: "SNELNX8881",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 7, title: "Aplicação" },
    nome: "SNELNX8882",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 8, title: "Aplicação" },
    nome: "SNELNX8883",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 9, title: "Aplicação" },
    nome: "SNELNX8884",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 10, title: "Banco de Dados" },
    nome: "SNELNX8885",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 11, title: "Banco de Dados" },
    nome: "SNELNX8886",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 12, title: "Banco de Dados" },
    nome: "SNELNX8887",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 13, title: "Aplicação" },
    nome: "SNELNX8888",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 14, title: "Mista" },
    nome: "SNELNX8889",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 15, title: "Aplicação" },
    nome: "SNELNX8890",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 16, title: "Mista" },
    nome: "SNELNX8891",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 17, title: "Banco de Dados" },
    nome: "SNELNX8892",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 18, title: "Banco de Dados" },
    nome: "SNELNX8893",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 19, title: "Banco de Dados" },
    nome: "SNELNX8894",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 20, title: "Mista" },
    nome: "SNELNX8895",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 21, title: "Aplicação" },
    nome: "SNELNX8896",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 22, title: "Aplicação" },
    nome: "SNELNX8897",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 23, title: "Banco de Dados" },
    nome: "SNELNX8898",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 24, title: "Aplicação" },
    nome: "SNELNX8899",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 25, title: "Banco de Dados" },
    nome: "SNELNX8900",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 26, title: "Mista" },
    nome: "SNELNX8901",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 27, title: "Aplicação" },
    nome: "SNELNX8902",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 28, title: "Banco de Dados" },
    nome: "SNELNX8903",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 29, title: "Aplicação" },
    nome: "SNELNX8904",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 30, title: "Aplicação" },
    nome: "SNELNX8905",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 31, title: "Aplicação" },
    nome: "SNELNX8906",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 32, title: "Aplicação" },
    nome: "SNELNX8907",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 33, title: "Aplicação" },
    nome: "SNELNX8908",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 34, title: "Banco de Dados" },
    nome: "SNELNX8909",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 35, title: "Banco de Dados" },
    nome: "SNELNX8910",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 36, title: "Banco de Dados" },
    nome: "SNELNX8911",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 37, title: "Aplicação" },
    nome: "SNELNX8912",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 38, title: "Mista" },
    nome: "SNELNX8913",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 39, title: "Aplicação" },
    nome: "SNELNX8914",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 40, title: "Banco de Dados" },
    nome: "SNELNX8915",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 41, title: "Banco de Dados" },
    nome: "SNELNX8916",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 42, title: "Aplicação" },
    nome: "SNELNX8917",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 43, title: "Banco de Dados" },
    nome: "SNELNX8918",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 44, title: "Banco de Dados" },
    nome: "SNELNX8919",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 45, title: "Banco de Dados" },
    nome: "SNELNX8920",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 46, title: "Banco de Dados" },
    nome: "SNELNX8921",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 47, title: "Aplicação" },
    nome: "SNELNX8922",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 48, title: "Banco de Dados" },
    nome: "SNELNX8923",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 49, title: "Banco de Dados" },
    nome: "SNELNX8924",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 50, title: "Banco de Dados" },
    nome: "SNELNX8925",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 51, title: "Mista" },
    nome: "SNELNX8926",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 52, title: "Aplicação" },
    nome: "SNELNX8927",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 53, title: "Aplicação" },
    nome: "SNELNX8928",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 54, title: "Banco de Dados" },
    nome: "SNELNX8929",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 55, title: "Aplicação" },
    nome: "SNELNX8930",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 56, title: "Banco de Dados" },
    nome: "SNELNX8931",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 57, title: "Banco de Dados" },
    nome: "SNELNX8932",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 58, title: "Banco de Dados" },
    nome: "SNELNX8933",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 59, title: "Mista" },
    nome: "SNELNX8934",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 60, title: "Mista" },
    nome: "SNELNX8935",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 61, title: "Banco de Dados" },
    nome: "SNELNX8936",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 62, title: "Banco de Dados" },
    nome: "SNELNX8937",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 63, title: "Aplicação" },
    nome: "SNELNX8938",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 64, title: "Mista" },
    nome: "SNELNX8939",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 65, title: "Aplicação" },
    nome: "SNELNX8940",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 66, title: "Banco de Dados" },
    nome: "SNELNX8941",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 67, title: "Banco de Dados" },
    nome: "SNELNX8942",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 68, title: "Mista" },
    nome: "SNELNX8943",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 69, title: "Banco de Dados" },
    nome: "SNELNX8944",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 70, title: "Aplicação" },
    nome: "SNELNX8945",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 71, title: "Banco de Dados" },
    nome: "SNELNX8946",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 72, title: "Mista" },
    nome: "SNELNX8947",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 73, title: "Banco de Dados" },
    nome: "SNELNX8948",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 74, title: "Banco de Dados" },
    nome: "SNELNX8949",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 75, title: "Mista" },
    nome: "SNELNX8950",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 76, title: "Banco de Dados" },
    nome: "SNELNX8951",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 77, title: "Aplicação" },
    nome: "SNELNX8952",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 78, title: "Mista" },
    nome: "SNELNX8953",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 79, title: "Banco de Dados" },
    nome: "SNELNX8954",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 80, title: "Mista" },
    nome: "SNELNX8955",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 81, title: "Mista" },
    nome: "SNELNX8956",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 82, title: "Mista" },
    nome: "SNELNX8957",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 83, title: "Banco de Dados" },
    nome: "SNELNX8958",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 84, title: "Banco de Dados" },
    nome: "SNELNX8959",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 85, title: "Mista" },
    nome: "SNELNX8960",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 86, title: "Mista" },
    nome: "SNELNX8961",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 87, title: "Aplicação" },
    nome: "SNELNX8962",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 88, title: "Mista" },
    nome: "SNELNX8963",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 89, title: "Aplicação" },
    nome: "SNELNX8964",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 90, title: "Aplicação" },
    nome: "SNELNX8965",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 91, title: "Banco de Dados" },
    nome: "SNELNX8966",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 92, title: "Banco de Dados" },
    nome: "SNELNX8967",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 93, title: "Banco de Dados" },
    nome: "SNELNX8968",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 94, title: "Mista" },
    nome: "SNELNX8969",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 95, title: "Banco de Dados" },
    nome: "SNELNX8970",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 96, title: "Aplicação" },
    nome: "SNELNX8971",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
  {
    camada: { id: 97, title: "Mista" },
    nome: "SNELNX8972",
    CPU: 23,
    MEMORIA: "1024GB",
    overhead: true,
  },
  {
    camada: { id: 98, title: "Aplicação" },
    nome: "SNELNX8973",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 99, title: "Banco de Dados" },
    nome: "SNELNX8974",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 100, title: "Banco de Dados" },
    nome: "SNELNX8975",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 101, title: "Banco de Dados" },
    nome: "SNELNX8976",
    CPU: 22,
    MEMORIA: "512GB",
    overhead: false,
  },
  {
    camada: { id: 102, title: "Aplicação" },
    nome: "SNELNX8977",
    CPU: 21,
    MEMORIA: "256GB",
    overhead: true,
  },
  {
    camada: { id: 103, title: "Banco de Dados" },
    nome: "SNELNX8978",
    CPU: 25,
    MEMORIA: "1GB",
    overhead: true,
  },
  {
    camada: { id: 104, title: "Aplicação" },
    nome: "SNELNX8979",
    CPU: 24,
    MEMORIA: "128GB",
    overhead: false,
  },
];

// GET: Fetch Todos
mock.onGet("api/system").reply((request) => {
  const system = data;
  return [200, JSON.parse(JSON.stringify(system))];
});
